spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 220320
    url: jdbc:postgresql://localhost:5432/security_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
